type CraftField = {
  id: string;
  name: string;
};

export const allCraftFields: CraftField[] = [
  { id: 'rebiteAlianca', name: 'REBITE/ALIANÇA' },
  { id: 'corano', name: 'CORANO' },
  { id: 'n70Plastif', name: 'N. 70 PLASTIF' },
  { id: 'vernizNAmassado', name: 'VERNIZ / N. AMASSADO' },
  { id: 'crsital020', name: 'CRSITAL 0,20' },
  { id: 'facto', name: 'FACTO' },
  { id: 'tactel', name: 'TACTEL' },
  { id: 'cordobaLigt', name: 'CÓRDOBA LIGT' },
  { id: 'coranoMescla', name: 'CORANO / MESCLA' },
  { id: 'lnaSucam', name: 'LNA SUCAM' },
  { id: 'atlanta', name: 'ATLANTA' },
  { id: 'begFlex', name: 'BEG-FLEX' },
  { id: 'coranoBb', name: 'Corano BB' },
  { id: 'resinado', name: 'RESINADO' },
  { id: 'cetim', name: 'CETIM' },
  { id: 'alkelin', name: 'ALKELIN' },
  { id: 'verniz', name: 'VERNIZ' },
  { id: 'naylon600', name: 'NAYLON 600' },
  { id: 'cristal020', name: 'CRISTAL 0,20' },
  { id: 'cristal030', name: 'CRISTAL 0,30' },
  { id: 'nylon70', name: 'NYLON 70' },
  { id: 'marcelha', name: 'MARCELHA' },
  { id: 'telaFelpsOuroPta', name: 'TELA FELPS OURO-PTA' },
  { id: 'telaFelpsCores', name: 'TELA FELPS CORES' },
  { id: 'naylon70', name: 'NAYLON 70' },
  { id: 'box12', name: 'BOX 1.2' },
  { id: 'perugia', name: 'PERUGIA' },
  { id: 'tnt60', name: 'TNT 60' },
  { id: 'tnt40', name: 'TNT 40' },
  { id: 'leitoso15mm', name: 'LEITOSO 15MM' },
  { id: 'feltroBolsasNiver', name: 'FELTRO BOLSAS (Niver)' },
  { id: 'nEspumado', name: 'N. ESPUMADO' },
  { id: 'espuma1cm', name: 'ESPUMA 1CM' },
  { id: 'newPrime', name: 'NEW-PRIME' },
  { id: 'laminadoTermico', name: 'LAMINADO TERMICO' },
  { id: 'espumaPack4mm', name: 'ESPUMA PACK 4mm' },
  { id: 'espumaPack6mm', name: 'ESPUMA PACK 6mm' },
  { id: 'vivo', name: 'VIVO' },
  { id: 'estaguete', name: 'ESTAGUETE' },
  { id: 'ziperNormal6', name: 'ZIPER NORMAL 6º' },
  { id: 'ziperNormal8', name: 'ZIPER NORMAL 8º' },
  { id: 'zipperN3', name: 'ZIPPER  Nº 3' },
  { id: 'cursorNormal5', name: 'CURSOR NORMAL 5º' },
  { id: 'cursorNormal8', name: 'CURSOR NORMAL 8º' },
  { id: 'cursorN3', name: 'CURSOR Nº 3' },
  { id: 'cursorEspecial', name: 'CURSOR ESPECIAL' },
  { id: 'fitaSilicone', name: 'FITA SILICONE' },
  { id: 'fita030Cbr', name: 'FITA 0,30 CBR' },
  { id: 'fita025', name: 'FITA-0,25' },
  { id: 'fita030', name: 'FITA-0,30' },
  { id: 'fita040', name: 'FITA-0,40' },
  { id: 'fita30Alg', name: 'FITA-30 ALG' },
  { id: 'fita40Alg', name: 'FITA-40 ALG' },
  { id: 'telaTuli', name: 'TELA TULI' },
  { id: 'telaAerada', name: 'TELA AERADA' },
  { id: 'cravoPlastico', name: 'CRAVO PLASTICO' },
  { id: 'regMetal025mm', name: 'REG. METAL 0,25mm' },
  { id: 'regMetal030mm', name: 'REG. METAL 0,30mm' },
  { id: 'regMetal040mm', name: 'REG. METAL 0,40mm' },
  { id: 'regPlas025mm', name: 'REG. PLÁS 0,25mm' },
  { id: 'regPlas030mm', name: 'REG. PLÁS 0,30mm' },
  { id: 'regPlas040mm', name: 'REG. PLÁS 0,40mm' },
  { id: 'passsadorMetal040mm', name: 'PASSSADOR METAL 0,40mm' },
  { id: 'cordao42', name: 'CORDÃO 4/2' },
  { id: 'cordao52', name: 'CORDÃO 5/2' },
  { id: 'cordaCruaGrossa', name: 'CORDA CRUA (GROSSA)' },
  { id: 'correnteBolinha', name: 'CORRENTE_BOLINHA' },
  { id: 'bPressao', name: 'B. PRESSÃO' },
  { id: 'bIma', name: 'B. IMÃ' },
  { id: 'botaoPressaoPlastico', name: 'BOTÃO  PRESSÃO PLÁSTICO' },
  { id: 'rebitePequeno', name: 'REBITE PEQUENO' },
  { id: 'puchadorDePlastico030mm', name: 'PUCHADOR DE PLÁSTICO 0,30mm' },
  { id: 'fecho025', name: 'FECHO 0,25' },
  { id: 'feiche030', name: 'FEICHE 0,30' },
  { id: 'feche040', name: 'FECHE 0,40' },
  { id: 'castelinho030Plas', name: 'CASTELINHO 0,30 PLÁS' },
  { id: 'trianguloPlastico30mm', name: 'TRIÂNGULO PLÁSTICO 30mm' },
  { id: 'trianguloMetal030', name: 'TRIÂNGULO METAL 0,30' },
  { id: 'mosqTriangolo030Metal', name: 'MOSQ.+TRIÂNGOLO 0,30 - METAL' },
  { id: 'meiaArgolaMetal040Grossa', name: 'MEIA ARGOLA METAL 0,40 (GROSSA)' },
  { id: 'meiaArgola030Metal', name: 'MEIA-ARGOLA 0,30 METAL' },
  { id: 'meiaArgola025Metal', name: 'MEIA-ARGOLA 0,25 METAL' },
  { id: 'ilhosN45', name: 'ILHÓS Nº 45' },
  { id: 'ilhosN5Garra', name: 'ILHÓS Nº 5 GARRA' },
  { id: 'mosqPlas030', name: 'MOSQ. PLÁS 0,30' },
  { id: 'mosq030Lx', name: 'MOSQ. 0,30 LX' },
  { id: 'mosqChaveiro', name: 'MOSQ. CHAVEIRO' },
  { id: 'papelao', name: 'PAPELÃO' },
  { id: 'peDeMalaPlastico', name: 'PÉ DE MALA / PLÁSTICO' },
  { id: 'macaquinhoFocinhoDePorco', name: 'Macaquinho Focinho de porco' },
  { id: 'mangueira5mm7mm', name: 'MANGUEIRA 5mm 7mm' },
  { id: 'gorgurao', name: 'GORGURÃO' },
  { id: 'vies030', name: 'VIÉS 0,30' },
  { id: 'elastico', name: 'ELASTICO' },
  { id: 'velco38m', name: 'VELCO - 38m' },
  { id: 'velcro16m', name: 'VELCRO 16m' },
  { id: 'ombreira40mm', name: 'OMBREIRA 40mm' },
  { id: 'fibraVirgem', name: 'FIBRA VIRGEM' },
  { id: 'carrinhoPlastico', name: 'CARRINHO PLÁSTICO' },
  { id: 'sublimacaoGrandePequena', name: 'SUBLIMAÇÃO / GRANDE / PEQUENA' },
  { id: 'etiqueta', name: 'ETIQUETA' },
  { id: 'embalagem', name: 'EMBALAGEM' },
  { id: 'linha', name: 'LINHA' },
  { id: 'pintura', name: 'PINTURA' },
  { id: 'comissao', name: 'COMISSÃO' },
  { id: 'costura', name: 'COSTURA' },
  { id: 'comissaoCostura', name: 'COMISSÃO COSTURA' },
  { id: 'fgtsFeriasEtc', name: 'FGTS-FÉRIAS ETC...' },
  { id: 'salarioFuncionarios', name: 'SALÁRIO FUNCIONÁRIOS' },
  { id: 'despExtras', name: 'DESP. EXTRAS' },
  { id: 'cristal', name: 'CRISTAL' },
  { id: 'cordoba', name: 'CÓRDOBA' },
  { id: 'coranoLisoLna1200MetalasseGde', name: 'CORANO_LISO / LNA_1200 / METALASSE GDE' },
  { id: 'lnaSucamTelaFelpsOuroPta', name: 'LNA SUCAM / TELA FELPS OURO-PTA' },
  { id: 'puMetalizadoCoranoTaurus', name: 'PU METALIZADO / CORANO TAURUS' },
  { id: 'venezaBegFlexTelaFelpsCores', name: 'VENEZA / BEG-FLEX / TELA FELPS CORES' },
  { id: 'lucroLona', name: 'Lucro LONA' },
  { id: 'lN70', name: 'L. N.70' },
  { id: 'lucroVerniz', name: 'Lucro VERNIZ' },
  { id: 'lCristal', name: 'L. CRISTAL' },
  { id: 'lFacto', name: 'L. FACTO' },
  { id: 'lucroTactel', name: 'Lucro TACTEL' },
  { id: 'lucroCordoba', name: 'Lucro CÓRDOBA' },
  { id: 'lucroCoranoLiso', name: 'Lucro CORANO LISO' },
  { id: 'lucroLonaSucam', name: 'Lucro LONA SUCAM' },
  { id: 'lucroAtlanta', name: 'Lucro ATLANTA' },
  { id: 'custoLona', name: 'CUSTO LONA' },
  { id: 'custoN70', name: 'CUSTO N.70' },
  { id: 'custoVerniz', name: 'CUSTO VERNIZ' },
  { id: 'custoCristal', name: 'CUSTO CRISTAL' },
  { id: 'custoFacto', name: 'CUSTO FACTO' },
  { id: 'custoTactel', name: 'CUSTO TACTEL' },
  { id: 'custoCordoba', name: 'CUSTO CÓRDOBA' },
  { id: 'custoCoranoLiso', name: 'CUSTO CORANO LISO' },
  { id: 'custoLnaSucamFelpsOuroPta', name: 'CUSTO LNA SUCAM / FELPS OURO_PTA' },
  { id: 'custoPuMetalizadoCoranoTaurus', name: 'CUSTO PU METALIZADO / CORANO TAURUS' },
  { id: 'custoAtlanta', name: 'CUSTO ATLANTA' },
  { id: 'custoVenezaBegFlexTelaFeplsCores', name: 'CUSTO VENEZA / BEG-FLEX / TELA FEPLS CORES' },
  { id: 'naylon600Lona', name: 'NAYLON 600 (LONA)' },
  { id: 'medidasDaBolsa', name: 'MEDIDAS  DA BOLSA' },
];